name: automate you app with github action
on:
  push:
    branches:
      - release
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-java@v2 #plugging to setup java
with:
  distribution: 'zulu'
  java-version: '11'
    - uses: subosito/flutter-actions@v2
      with:
        flutter-version: '3.7.1'
          - run: flutter pub get
          - run: flutter test
          - run: flutter build apk
          - run: flutter build appbundle

