name: automate you app with github action
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs_on: macos-latest
    steps:
      - uses: actions/checkoutv@2
      - uses: actions/setup-java@v2
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test







