name: automate you app with github action
'on':
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: macos-latest
    distribution: zulu
    java-version: '11'
    flutter-version: 3.7.1
steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-java@v2
  - uses: subosito/flutter-action@v2
with:
  - run: flutter pub get
  - run: flutter test
  - run: flutter build apk
  - run: flutter build appbundle
  - name: Create github artifact release
    uses: ncipollo/release-action@v1
    with:
      artifacts: >-
        build/app/outputs/apk/release/*:
        apk,build/app/outputs/bundle/release/app-release: aab
      token: '${{ secrets.GITHUB_TOKEN }}'
      comit:
        - name: Upload app bundle artifact
          uses: actions/upload-artifact@v2
          with:
            name: appbundle
            path: build/app/outputs/bundle/release/app-release.aab
